baseurl: /
description: >
      ModSpace is a CoWorking Space in Modesto, CA
email: geektech2000@gmail.com
encoding: utf-8
github: https://github.com/mod-space/mod-space.github.io
markdown: kramdown
title: ModSpace
url: modspace.net
sass:
  style: compressed
gems:
  - jekyll-sitemap
